Re-organization complete.
- Added licenses Golf3
- Eliminated old examples
- Updated existing examples to show some more features, expand on
  explanation
- Minor bug fixes to check for existence of test specfile and prevent
  rerun directive from erroring out of no tests have been run

diff --git a/testy b/testy
--- a/testy
+++ b/testy
@@ -2,7 +2,8 @@
 #
 # A script to automate testing programs on the command line.
 # author:  Chris Kauffman <kauffman@umn.edu>
-# RELEASE: Mon 17 Feb 2020 09:42:58 PM CST 
+# license: GPLv3-or-later
+# RELEASE: Tue 18 Aug 2020 02:45:22 PM CDT 
 
 read -r -d '' usage <<EOF
 usage:    testy <testfile.org> [test# test# ...]
@@ -24,7 +25,7 @@ input/output. Each test can have multiple sessions. As a session is
 found it is run. If the session fails, subsequent sessions for that
 test are not run.
 
-Sample input:
+Sample input file (sample_tests.org):
 ================
 #+TITLE: Sample Tests
 
@@ -88,14 +89,16 @@ They will change the behavior of how the test data is interpretted.
 Global variables that are usually specified at the beginning of a test
 file before any other tests.
 
-PROGRAM="bash"           : program to run/test if no option is specified
-PROMPT=">>"              : prompt to honor if none is specified
+PROGRAM="bash"           : program to run/test; input is fed to this program
+PROMPT=">>"              : prompt that indicates input to the program
 ECHOING="input"          : {input, both} for program input echoing style, 
                            "input" means the program echoes only input provided by testy, testy will add back in prompts
                            "both" echoes both prompt and input so testy won't add back anything
-PREFIX="test"            : prefix for output files
+                            NOTE: testy does not support mocked interaction tests for programs that don't echo input 
+                            as this is generally hard to do
+PREFIX="test"            : prefix for output files, often changed to reflect program name like 'myprog'
 RESULTDIR="test-results" : directory where the resutls will be written
-TIMEOUT="5s"             : maximum time for the test before it is failed due to timeout
+TIMEOUT="5s"             : maximum time to complete test before it is failed due to timeout
 POST_FILTER=""           : program to adjust output from test before evaluating, run as 'cat output | post_filter > actual.tmp'
 USE_VALGRIND="0"         : set to 1 to run programs under Valgrind which checks for memory errors
 VALGRIND_REACHABLE="1"   : under valgrind, report errors if memory is still reachable at the end of the program
@@ -143,15 +146,15 @@ PREFIX=${PREFIX:-"test"}                              # prefix for the files tha
 RESULTDIR=${RESULTDIR:-"test-results"}                # directory where the resutls will be written
 RESULTRAW=${RESULTRAW:-"$RESULTDIR/raw"}              # directory where actual / expect / valgrind results are stored
 TIMEOUT=${TIMEOUT:-"5s"}                              # time after which to kill a test, passed to 'timeout' command and program_wait();
-LONGTICKS=${LONGTICKS:-"8"}                           # number of ticks to wait starting a program w/ valgrind during TESTY_MULTI
 POST_FILTER=${POST_FILTER:-""}                        # run this progam on output to adjust it if needed
 USE_VALGRIND=${USE_VALGRIND:-"0"}                     # use valgrind while testing
 VALGRIND_REACHABLE=${VALGRIND_REACHABLE:-"1"}         # report valgrind errors if memory is still reachable
 SKIPDIFF=${SKIPDIFF:-"0"}                             # skip diffing results, useful if checking valgrind but actual output can vary
+VALGRIND_OPTS=${VALGRIND_OPTS:-""}                    # additional options to valgrind, 
 TICKTIME=${TICKTIME:-"0.1"}                           # multi: amount of time to wait in between test commands
 VALGRIND_START_TICKS=${VALGRIND_START_TICKS:-"8"}     # multi: number of ticks to wait when starting valgrind programs which take a while
-VALGRIND_OPTS=${VALGRIND_OPTS:-""}                    # additional options to valgrind, 
 # VALGRIND_OPTS="--suppressions=test_valg_suppress_leak.conf"
+# LONGTICKS=${LONGTICKS:-"8"}                           # number of ticks to wait starting a program w/ valgrind during TESTY_MULTI
 
 # INPUT_STYLE="normal"
 
@@ -169,15 +172,15 @@ function reset_options(){                             # reset options to default
     resultdir=$RESULTDIR
     resultraw=$RESULTRAW
     timeout=$TIMEOUT
-    longticks=$LONGTICKS
     post_filter=$POST_FILTER
     use_valgrind=$USE_VALGRIND
     valgrind_reachable=$VALGRIND_REACHABLE
     skipdiff=$SKIPDIFF
+    valgrind_opts=$VALGRIND_OPTS    
     ticktime=$TICKTIME
     valgrind_start_ticks=$VALGRIND_START_TICKS
-    valgrind_opts=$VALGRIND_OPTS    
     # input_style=$NORMAL
+    # longticks=$LONGTICKS
 }    
 
 # fail if a tool is not found, used to check for utilities like timeout and valgrind
@@ -373,7 +376,7 @@ function program_start () {
 
     if [[ "$use_valgrind" == "1" ]]; then
         debug "use_valgrind=1, long ticks while starting program"
-        for i in $(seq $longticks); do
+        for i in $(seq ${valgrind_start_ticks}); do
             tick
         done
     else
@@ -757,7 +760,7 @@ function run_testy_multi_session(){
     {
         printf '(TEST %d) %s\n' "$testnum" "$test_title"
         printf 'COMMENTS:\n'
-        printf "${comments}\n" 
+        printf "%b\n" "${comments}"
         printf 'program: %s\n' "$program"
         printf '\n'
         # printf '%s\n' '- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
@@ -1030,7 +1033,7 @@ function run_test_session(){
         {                                             # begin capturnig output for results file
            printf '(TEST %d) %s\n' "$testnum" "$test_title"
            printf 'COMMENTS:\n'
-           printf "%s\n" "${comments}"
+           printf "%b\n" "${comments}"
            printf 'program: %s\n' "$program"
            printf "Failure messages:\n"
            for msg in "${fail_messages[@]}"; do       # iterate through faiure messages
@@ -1106,6 +1109,11 @@ debug "alltests='$alltests"
 if [[ "$specfile" = "--help" ]]; then                 # check for --help option
     printf "%s\n" "$usage"                            # print usage and exit
     exit 0
+fi
+
+if [[ ! -r "$specfile" ]]; then                       # check specfile exists / readable
+    printf "ERROR: could not open '%s' for reading\n" "$specfile" > /dev/stderr
+    exit 1
 fi
 
 deps="timeout stdbuf awk $SEDCMD grep diff"           # check for baseline necessary tools
@@ -1244,6 +1252,15 @@ for testnum in $alltests; do                          # Iterate over all tests t
                 end=$((session_end_line+1))           # #+END_SRC line
                 linenum=$((beg-1))
                 debug "^^ Re-running session on lines $beg to $end"
+                if (( $beg == 0 )); then
+                    {
+                        printf "ERROR in test %s with directive '#+TESTY_RERUN'\n" "$testnum" 
+                        printf "Alas, testy does not support rerunning a test that hasn't already been run\n" 
+                        printf "Try running all tests instead\n"
+                    } > /dev/stderr
+                    exit 1
+                fi
+
                 if [[ "$program" == "TESTY_MULTI" ]]; then
                     run_testy_multi_session <<< "$(sed -n "${beg},${end}p" $specfile)"
                 else
