Added quotations where possible to prevent word splitting, prevented direct passing of parameters to printf format string

diff --git a/testy b/testy
--- a/testy
+++ b/testy
@@ -193,15 +193,15 @@ function updateline(){                                # processes $line to set s
 # from the test session.
 function run_test_session(){
 
-    mkdir -p $resultdir                               # set up test results directory
-    mkdir -p $resultraw
+    mkdir -p "$resultdir"                               # set up test results directory
+    mkdir -p "$resultraw"
     result_file=$(printf "%s/%s-%02d-result.tmp" "$resultdir" "$prefix" "$testnum")
     actual_file=$(printf "%s/%s-%02d-actual.tmp" "$resultraw" "$prefix" "$testnum")
     expect_file=$(printf "%s/%s-%02d-expect.tmp" "$resultraw" "$prefix" "$testnum")
     valgrd_file=$(printf "%s/%s-%02d-valgrd.tmp" "$resultraw" "$prefix" "$testnum")
-    rm -f ${actual_file} ${expect_file} ${result_file} ${valgrd_file}
+    rm -Rf "${actual_file}" "${expect_file}" "${result_file}" "${valgrd_file}"
 
-    if [[ "$use_valgrind" = 1 ]]; then
+    if [[ "$use_valgrind" == 1 ]]; then
         VALGRIND="${VALGRIND_PROG} --log-file=${valgrd_file}"
     else
         VALGRIND=""
@@ -210,10 +210,10 @@ function run_test_session(){
     toprog_fifo=$(mktemp --tmpdir testy_to.XXXXXX)    # set up communication with the program being tested
     fromprog_file=$(mktemp --tmpdir testy_from.XXXXXX)
     debug "toprog_fifo: $toprog_fifo"
-    debug "fromprog_fifo: $fromprog_fifo"
-    rm -f ${toprog_fifo} ${fromprog_file}             # remove just in case
+    debug "fromprog_file: $fromprog_file"
+    rm -Rf "${toprog_fifo}" "${fromprog_file}"             # remove just in case
 
-    mkfifo $toprog_fifo                               # create the fifos
+    mkfifo "$toprog_fifo"                               # create the fifos
     # mkfifo $fromprog_fifo
 
     # RUN THE PROGRAM
@@ -224,12 +224,12 @@ function run_test_session(){
     # - input is read from a fifo from the specfile
     # - output is directed to a file
     debug "running: '$TIMEOUTCMD $timeout $STDBUF $VALGRIND $program <${toprog_fifo} &> ${fromprog_file} &'"
-    $TIMEOUTCMD $timeout $STDBUF $VALGRIND $program <${toprog_fifo} &> ${fromprog_file} &
+    $TIMEOUTCMD $timeout $STDBUF $VALGRIND $program <"${toprog_fifo}" &> "${fromprog_file}" &
     pid=$!
     debug "child pid: $pid"
 
-    # open to after running the program or testy will stall 
-    exec {to}>${toprog_fifo}                          # open connection to fifo for writing
+    # open to after running the program or testy will stall
+    exec {to}>"${toprog_fifo}"                          # open connection to fifo for writing
     debug "to fd: $to"
 
     status="$PASS_STATUS"                             # initial status, change to 'FAIL' if things go wrong
@@ -280,7 +280,7 @@ function run_test_session(){
     debug "wait returned: $retcode"
 
     debug "removing to fifo"
-    rm ${toprog_fifo}                                 # ${toprog_fifo}
+    rm -Rf "${toprog_fifo}"                                 # ${toprog_fifo}
 
     case "$retcode" in                                # inspect return code for errors
         "$VALG_ERROR")
@@ -299,13 +299,13 @@ function run_test_session(){
 
     if [[ "$use_valgrind" = "1" ]] &&                 # if valgrind is on
        [[ "$valgrind_reachable" = "1" ]] &&           # and checking for reachable memory
-       ! awk '/still reachable:/{if($4 != 0){exit 1;}}' ${valgrd_file};
+       ! awk '/still reachable:/{if($4 != 0){exit 1;}}' "${valgrd_file}";
     then                                              # valgrind log does not contain 'reachable: 0 bytes'
         status="FAIL"
         fail_messages+=("FAILURE: Valgrind reports reachable memory, may need to add free() or fclose()")
     fi
 
-    cp ${fromprog_file} ~/fromprog.tmp
+    cp "${fromprog_file}" ~/fromprog.tmp
 
     # ADDING IN PROMPTS TO ECHOED INPUT
     #
@@ -322,7 +322,7 @@ function run_test_session(){
     # the wrong spot.
     if [[ "$echoing" = "input" ]]; then               # program may only echo input necessitating adding prompts to output
         idx=0                                         # index for input line
-        exec {mod}>${fromprog_file}.mod
+        exec {mod}>"${fromprog_file}.mod"
         while read -r || [[ "$REPLY" != "" ]]; do     # read from output file into default REPLY var, second condition catches last line which may not end with a newline char
             if (( idx < ${#all_input[@]} )) &&        # still in bounds for input lines
                [[ "${all_input[idx]}" = "$REPLY" ]];  # input line matches the program output
@@ -332,28 +332,28 @@ function run_test_session(){
                 debug "added prompt to input $idx: $REPLY"
             fi;
             printf '%s\n' "$REPLY" >&$mod             # output the (un)modified line into the modified file
-        done < ${fromprog_file}                       # reading from the original output file
+        done < "${fromprog_file}"                       # reading from the original output file
         exec {mod}>&-                                 # close the modified file
-        mv ${fromprog_file}.mod ${fromprog_file}      # copy modified file back to original
+        mv "${fromprog_file}.mod" "${fromprog_file}"      # copy modified file back to original
     fi
 
     if [[ "$post_filter" != "" ]]; then               # use a filter to post-process the output
         debug "running post filter '$post_filter'"
-        cat ${fromprog_file} | ${post_filter} > ${fromprog_file}.tmp
-        mv ${fromprog_file}.tmp ${fromprog_file}
+        cat "${fromprog_file}" | ${post_filter} > "${fromprog_file}.tmp"
+        mv "${fromprog_file}.tmp" "${fromprog_file}"
     fi
 
     # To avoid confusion, replace message from timeout program with
     # easier to interpret Segfault Message
     $sedCmd -i'' 's/timeout: the monitored command dumped core/Segmentation Fault/' "${fromprog_file}"
 
-    mv ${fromprog_file} ${actual_file}                # copy temp file to final destination
+    mv "${fromprog_file}" "${actual_file}"                # copy temp file to final destination
 
     # extract expected output from test file, filter #+TESTY_ , store result in expect_file
     cat "$specfile" | \
         $sedCmd -n "${session_beg_line},${session_end_line}p" | \
         grep -v '^#+TESTY_' \
-        > ${expect_file}
+        > "${expect_file}"
 
     # Try to compute the width of expected/actual outputs to make the
     # side-by-side diff as narrow as possible. 'diff -y -W' is a bit
@@ -364,8 +364,8 @@ function run_test_session(){
     # the left EXPECT column is narrow while the right ACTUAL column
     # wide. Later code filters to remove extraneous whitespace from
     # the left column.
-    actual_width=$(awk 'BEGIN{max=16}{w=length; max=w>max?w:max}END{print max}' $actual_file)
-    expect_width=$(awk 'BEGIN{max=16}{w=length; max=w>max?w:max}END{print max}' $expect_file)
+    actual_width=$(awk 'BEGIN{max=16}{w=length; max=w>max?w:max}END{print max}' "$actual_file")
+    expect_width=$(awk 'BEGIN{max=16}{w=length; max=w>max?w:max}END{print max}' "$expect_file")
     col_width=$((actual_width > expect_width ? actual_width : expect_width))
     total_width=$((col_width*2 + 3))                  # width to pass to diff as -W
     debug "actual_width $actual_width"
@@ -396,7 +396,7 @@ function run_test_session(){
         {                                             # begin capturnig output for results file
            printf '(TEST %d) %s\n' "$testnum" "$test_title"
            printf 'COMMENTS:\n'
-           printf "${comments}\n" 
+           printf "%s\n" "${comments}"
            printf 'program: %s\n' "$program"
            printf "Failure messages:\n"
            for msg in "${fail_messages[@]}"; do       # iterate through faiure messages
@@ -406,11 +406,11 @@ function run_test_session(){
 
            if [[ "$diffreturn" != "0" ]]; then        # show differences between expect and actual
                printf "%s\n" "--- Side by Side Differences ---"
-               printf "%s\n" "- Expect output in: $expect_file" 
-               printf "%s\n" "- Acutal output in: $actual_file" 
+               printf "%s\n" "- Expect output in: $expect_file"
+               printf "%s\n" "- Actual output in: $actual_file"
                printf "%s\n" "- Differing lines have a character like '|' in the middle\n"
                printf "%-${col_width}s   %-${col_width}s\n" "==== EXPECT ====" "==== ACTUAL ===="
-               $SDIFF -W $total_width $expect_file $actual_file 
+               $SDIFF -W $total_width "$expect_file" "$actual_file"
                printf "%s\n" "--- Line Differences ---"
                printf "%s\n" "$diffresult"
                printf "\n"
@@ -418,10 +418,10 @@ function run_test_session(){
 
            if [[ "$use_valgrind" = "1" ]]; then       # show valgrind log if enabled and test failed
                printf "%s\n" "--- Valgrind Log from: $valgrd_file ---"
-               cat $valgrd_file
+               cat "$valgrd_file"
                printf "\n"
            fi
-        } &> ${result_file}                           # end of results file output
+        } &> "${result_file}"                           # end of results file output
 
         # The below eliminate extra spaces in diff results mostly for
         # the left EXPECT column that would make the output very wide.
@@ -452,7 +452,7 @@ unset BASH_ENV                                        # ensure subshells don't s
 
 funcs=$(declare -x -F | awk '{print $3}')             # eliminate any exported functions in bash
 for f in $funcs; do                                   # as these are output with the -v option
-    unset -f $f;
+    unset -f "$f";
 done
 
 
@@ -472,7 +472,7 @@ debug "alltests='$alltests"
 
 
 if [[ "$specfile" = "--help" ]]; then                 # check for --help option
-    printf "$usage\n"                                 # print usage and exit
+    printf "$%s\n" "$usage"                                 # print usage and exit
     exit 0
 fi
 
@@ -515,7 +515,7 @@ while read -r; do                                     # read from test file, -r 
             fi
             ((testnum++))                             # reset and start collecting text for the new test
             test_beg_line+=("$linenum")
-            if (( ${#rest} > $TEST_TITLE_WIDTH ));    # calculate maximum width of any title
+            if (( ${#rest} > TEST_TITLE_WIDTH ));    # calculate maximum width of any title
             then
                 TEST_TITLE_WIDTH=${#rest}
             fi
@@ -535,7 +535,7 @@ while read -r; do                                     # read from test file, -r 
             debug "^^ Ignoring line in first pass"
             ;;
     esac
-done < $specfile
+done < "$specfile"
 
 endline=$(( linenum ))                                # append the last test end
 test_end_line+=("$endline")
@@ -575,7 +575,7 @@ failcount=0
 
 printf "============================================================\n"
 if [[ "$global_title" = "" ]]; then
-    printf "== testy $specfile\n"
+    printf "== testy %s\n" "$specfile"
 else
     printf "== $specfile : %s\n" "$global_title"
 fi
@@ -636,15 +636,15 @@ done
 # Final Output
 passcount=$((testcount-failcount))                    # calculate number of tests passed
 printf "============================================================\n"
-printf "RESULTS: $passcount / $testcount tests passed\n"
+printf "RESULTS: %s / %s tests passed\n" "$passcount" "$testcount"
 
 debug "SHOW: $SHOW"
 if [[ "$SHOW" -eq 1 && "${#fail_files[@]}" -gt 0 ]]; then # show failure results if requested
     printf "\n\n"
     printf "FAILURE RESULTS\n"
     printf "%s\n" "----------------------------------------"
-    for f in "${fail_files[@]}"; do                   # iteratre overa ll failure files outputing them
-        cat $f
+    for f in "${fail_files[@]}"; do                   # iterate over all failure files, outputting them
+        cat "$f"
         printf "%s\n" "----------------------------------------"
     done
 fi
